### ISSUE TITLE
Exe not displaying in xworm after launch.

### ISSUE THREAD

**Issue by Waterwhipt** [Shinyenigma/XWorm-RAT#8]
I am testing this on an RDP and there's only 2 problems I found. When I open the program, I get an error that GEOip.dat couldn't be found in resource folder, but It can be fixed by copying it in too. But after I run the builder to generate the .exe, when I open it there is no connection. I used local 127... ip and 7000 port. But thank you for uploading that's very generous of you.

**Comment by Shinyenigma** [comment]
Thanks for issue
Did you use dedicated server or PC? Try building on server
Anyway, I'll try to fix problems soon

**Comment by Waterwhipt** [comment]
What kind of dedicated server? I used RDP windows 10 PC but do you mean to change the IP to a server to connect to? I tried to use playit.gg but with no result so far. Perhaps if you have license you can get an updated version for free? 
Ill keep playing around with it for now 👍

**Comment by Shinyenigma** [comment]
Maybe I know how to fix the problem
Will try to do it tomorrow

**Comment by Waterwhipt** [comment]
Thank you! I'll be checking in !
